name: Performance Test
on:
  pull_request:
    branches:
    - 'dbartol/perf'
jobs:
  new:
    name: Measure performance of new code
    runs-on:
    - windows-latest
    steps:
    - name: Checkout QL
      uses: actions/checkout@v1
    - name: Download CodeQL CLI
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: github/codeql-cli-binaries
        tag: v2.0.1
        path: cli
        file: codeql.zip
