name: Performance Test
on:
  pull_request:
    branches:
    - 'dbartol/perf'
jobs:
  new:
    name: Measure performance of new code
    runs-on:
    - windows-latest
    steps:
    - name: Checkout QL
      uses: actions/checkout@v1
    - name: Cache CodeQL CLI
      id: cache
      uses: actions/cache@v1
      with:
        path: codeql-cli
        key: codeql-cli-v2.0.1
    - name: Download CodeQL CLI
      if: steps.cache.outputs.cache-hit != 'true'
      shell: pwsh
      run: Invoke-WebRequest -Uri https://github.com/github/codeql-cli-binaries/releases/download/v2.0.1/codeql.zip -OutFile codeql.zip
    - name: Unzip CodeQL CLI
      if: steps.cache.outputs.cache-hit != 'true'
      shell: pwsh
      run: Expand-Archive -Path codeql.zip -DestinationPath codeql-cli
    - name: Download Database
      shell: pwsh
      run: Invoke-WebRequest -Uri 'https://lgtm.com/api/v1.0/snapshots/2034240708/cpp' -Headers @{ Authorization = 'bearer ${{ secrets.LGTM_SNAPSHOT_DOWNLOAD }}'} -OutFile microsoft_ChakraCore.zip
    - name: Unzip Database
      shell: pwsh
      run: Expand-Archive -Path microsoft_ChakraCore.zip -DestinationPath microsoft_ChakraCore
    - name: Run CodeQL
      shell: pwsh
      run: |
        &'codeql-cli/codeql/codeql.cmd' database analyze database --format sarifv2 --output results.sarif
