name: Performance Test
on:
  pull_request:
    branches:
    - 'dbartol/perf'
jobs:
  new:
    name: Measure performance of new code
    strategy:
      matrix:
        node_id: [0, 1, 2]
      fail-fast: false
    runs-on:
    - windows-latest
    steps:
    - name: Checkout QL
      uses: actions/checkout@v1
    - name: Environment
      shell: powershell
      run: |
        Get-WmiObject win32_logicaldisk
        Get-ChildItem env:
    - name: Cache CodeQL CLI
      id: cache
      uses: actions/cache@v1
      with:
        path: codeql-cli
        key: codeql-cli-v2.0.1
    - name: Download CodeQL CLI
      if: steps.cache.outputs.cache-hit != 'true'
      shell: pwsh
      run: Invoke-WebRequest -Uri https://github.com/github/codeql-cli-binaries/releases/download/v2.0.1/codeql.zip -OutFile codeql.zip
    - name: Unzip CodeQL CLI
      if: steps.cache.outputs.cache-hit != 'true'
      shell: pwsh
      run: Expand-Archive -Path codeql.zip -DestinationPath codeql-cli
    - name: Download Database
      shell: pwsh
      run: Invoke-WebRequest -Uri 'https://lgtm.com/api/v1.0/snapshots/2034240708/cpp' -Headers @{ Authorization = 'bearer ${{ secrets.LGTM_SNAPSHOT_DOWNLOAD }}'} -OutFile microsoft_ChakraCore.zip
    - name: Unzip Database
      shell: pwsh
      run: Expand-Archive -Path microsoft_ChakraCore.zip -DestinationPath microsoft_ChakraCore
    - name: Run CodeQL
      shell: pwsh
      run: |
        $DatabasePath = Get-ChildItem microsoft_ChakraCore
        for ($i = 0; $i -lt 5; $i += 1) {
          &'codeql-cli/codeql/codeql.cmd' database cleanup --mode=brutal $DatabasePath.FullName
          if ($LASTEXITCODE -ne 0) {
            throw "CodeQL command failed with exit code ${LASTEXITCODE}"
          }
          &'codeql-cli/codeql/codeql.cmd' database analyze $DatabasePath.FullName cpp/ql/test/library-tests/ir/constant_func/constant_func.ql --format csv --output results.csv --additional-packs cpp/ql/src --rerun
          if ($LASTEXITCODE -ne 0) {
            Write-Host "CodeQL command failed with exit code ${LASTEXITCODE}"
          }
        }
    - name: Fail
      shell: pwsh
      run: throw "Fail!"
